#include "levels/alley/texture_include.inc.c"
#include "levels/alley/area_1/collision.inc.c"
#include "levels/alley/area_1/macro.inc.c"
#include "levels/alley/area_1/spline.inc.c"
#include "levels/alley/model.inc.c"
